name: Release

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build Native Gems with Rake-Compiler-Dock
    strategy:
      matrix:
        os: [ubuntu-latest]
        target:
          - default
          - aarch64-linux-gnu
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - aarch64-linux-musl
          - x86_64-darwin
          - arm64-darwin

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install APT dependencies
        run: xargs sudo apt-get install -y --no-install-recommends < Aptfile

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: bundle install
        run: bundle install

      - name: Render Templates
        run: bundle exec rake templates

      - name: Compile Herb
        run: bundle exec rake make

      - name: Precompile gem
        run: |
          if [ "${{ matrix.target }}" = "default" ]; then
            bundle exec rake build
          else
            bundle exec rake gem:${{ matrix.target }}
          fi
